# permissions for end users to view kubehosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubehosts-viewer-role
rules:
- apiGroups:
  - batch.github.com
  resources:
  - kubehosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.github.com
  resources:
  - kubehosts/status
  verbs:
  - get
