---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test1
  name: hosts-config-1
data:
  hosts: |
    # 127.0.0.1 localhost 
    # this is a test
    # yy
    # ii
    dd
    ff
    gg
    kk
    
